name: aws
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Launcher
      run: |
        Invoke-WebRequest https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/download/v1.0.0-pre/sd.webui.zip -OutFile sd.webui.zip
    - name: Extracting File
      run: Expand-Archive sd.webui.zip
    - name: update bat
      run: cmd /c update.bat
    - name: run
      run: cmd /c run.bat
