name: aws
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Launcher
      run: |
        Invoke-WebRequest https://github.com/AUTOMATIC1111/stable-diffusion-webui/archive/refs/heads/master.zip -OutFile stable-diffusion-webui-master.zip
    - name: Extracting File
      run: Expand-Archive stable-diffusion-webui-master.zip
    - name: run
      run: cmd /c webui-user.bat
